apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iscsi-democratic-csi
  namespace: argocd
  annotations:
    argocd.argoproj.io/depends-on: argocd/democratic-csi-snapshot-controller
spec:
  project: default
  source:
    repoURL: https://democratic-csi.github.io/charts/
    targetRevision: 0.15.0
    chart: democratic-csi
    helm:
      # Use your values with secret references
      values: |
        csiDriver:
          name: "org.democratic-csi.iscsi"
        storageClasses:
          - name: freenas-iscsi-csi
            defaultClass: false
            reclaimPolicy: Delete
            volumeBindingMode: Immediate
            allowVolumeExpansion: true
            parameters:
              fsType: ext4
              detachedVolumesFromSnapshots: "false"
            mountOptions: []
            secrets:
              provisioner-secret:
              controller-publish-secret:
              node-stage-secret:
              node-publish-secret:
              controller-expand-secret:
        volumeSnapshotClasses:
        - name: iscsi-snapshot
          parameters:
            detachedSnapshots: "true"
        driver:
          existingConfigSecret: truenas-iscsi-driver-config
          config:
            driver: freenas-api-iscsi

  destination:
    server: https://kubernetes.default.svc
    namespace: democratic-csi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true