# democratic-csi-argocd.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: democratic-csi-snapshot-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://democratic-csi.github.io/charts/
    targetRevision: 0.3.0
    chart: snapshot-controller

  destination:
    server: https://kubernetes.default.svc
    namespace: democratic-csi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true